### ISSUE TITLE
determining the peak summit

### ISSUE THREAD

**Issue by oriolfornes** [LHentges/LanceOtron#11]
Hi, is there's a way to determine the summits of lanceotron peaks, or should I use peak centers? Thanks!

**Comment by LHentges** [comment]
Depending on your usage, peak centres tend to work pretty well. That being said, they're not the same and others have requested this feature too.

Please bear with me for a little while, I'm going to leave this issue open for now and try and add this in the next few weeks.

**Comment by LHentges** [comment]
This has also now made its way to conda! Thanks for your input, and please let me know if you have any other feature requests in the future.
