### ISSUE TITLE
[Web interface] Stuck on loading

### ISSUE THREAD

**Issue by julianstanley** [LHentges/LanceOtron#15]
Hi there,

Here's an issue on the [web interface](https://lanceotron.molbiol.ox.ac.uk) (hopefully this is an appropriate place!).

I get a similar error on Chrome, Firefox, and Safari on an M1 Mac. 

**Issue**
Once the analysis is complete, the "View/Download Peaks" interface is stuck loading. In the console, I get a `TypeError: undefined is not an object (evaluating 'this.temp_data.views')
loadInData — mlview_base.js:43`.

<img width="500" alt="image" src="https://github.com/LHentges/LanceOtron/assets/22749289/4c44ace0-01d4-48a0-b402-81a3871ff540">

**Steps to reproduce**

1. Find and Score Peaks -> Start
<img width="120" alt="image" src="https://github.com/LHentges/LanceOtron/assets/22749289/57b5136c-3b0b-4818-afbf-40fe88355015">

2. Add name and description. Genome is "other" (in my case, NC_000964.2, an E. coli K12 assembly). --> Create
<img width="240" alt="image" src="https://github.com/LHentges/LanceOtron/assets/22749289/69ffab60-9cfa-43da-a1cc-ce8ad2354f0c">

3. Add publically-accessible bigWig. (We can use `https://gwlilabwigs.s3.amazonaws.com/171030/171030Li_Ecoli_pnp_rend_5_f.bw`, I got the same error with a few other files and after uploading from local).

4. Select any model. I'll go with `wide-and-deep_mar-2021`. 
<img width="200" alt="image" src="https://github.com/LHentges/LanceOtron/assets/22749289/6ede3ad2-800b-4488-861f-425779d4c47c">

5. Wait for the processing to finish. 

Once the processing is finished, I get the error posted above
<img width="500" alt="image" src="https://github.com/LHentges/LanceOtron/assets/22749289/38cc49ba-8f4b-4753-bc18-265efa0a206e">
<img width="500" alt="image" src="https://github.com/LHentges/LanceOtron/assets/22749289/73c60d74-ddcc-4b23-bc2d-9ba79b3830ff">

**Comment by martinSergeant** [comment]
Thankyou for your feedback. The problem is that no peaks were called by the program, obviously there should be a more graceful way of the webapp handling this.  Although Lanceotron is agnostic to the genome being analysed, its model was generated  from CHiPseq/ATACseq data. The signal in the track (see below) was not handled well by the model. Out of curiosity what technique was used to generate the track?

![peaks](https://github.com/LHentges/LanceOtron/assets/9353045/8d28a469-a02a-46f7-9d8a-d351901dfcef)

**Comment by julianstanley** [comment]
Ah -- that makes sense, thank you!

This data came from [RendSeq](https://www.cell.com/cell/pdf/S0092-8674(18)30287-3.pdf), which is enriched for 5' and 3' RNA ends, while keeping the relative abundances of that RNA intact.

We have some methods for calling peaks in our data (that we're starting to write up!), so when we read your paper we were curious whether your model could also pick up our peaks! Sounds like the data is just too different

**Comment by LHentges** [comment]
That's really interesting! Yes I'm afraid LoTron's just not going to be able to handle these data. I'm playing around with making it more flexible, but it's still in a nascent state at this point.

Good luck writing up, and I'll keep an eye out for your work! Feel free to shoot me a message if there's anything I can help with.
