### ISSUE TITLE
Is it possible to analyze using multiple inputs?

### ISSUE THREAD

**Issue by mcsimenc** [LHentges/LanceOtron#17]
If I run `lanceotron callPeaksInput` with two `-i` flags it starts to run. Does this mean it is somehow incorporating the information from both background samples, or maybe the last one only? Thanks!

**Comment by LHentges** [comment]
Sorry to say it's only using the file from the last input!

It's not designed to handle multiple inputs natively, but there are a couple of ways I can think of that could achieve that effect.

1. Normalize input 1 (RPKM/CPM or whatever your preferred method), normalize input 2, combine input 1 and 2, normalize input1+2, then use that as the single input file in LanceOtron
2. Run LanceOtron twice - once with input 1 and again with input 2, and combine the p-values from each region using Fisher's method

Apologies for the inconvenience, hope this helps!

**Comment by mcsimenc** [comment]
Thanks for filling me in!
