### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './standard_scaler_wide_v5_03.p'

### ISSUE THREAD

**Issue by Kevin-Brockers** [LHentges/LanceOtron#2]
Dear all,

I just tried to run find and score peaks and I get the following error:

line 124, in <module>
    standard_scaler_wide = pickle.load(open('./standard_scaler_wide_v5_03.p', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: './standard_scaler_wide_v5_03.p'

Do you know what I do wrong?

All best,
Kevin

**Comment by LHentges** [comment]
Hi Kevin,

At first glance I thought this was an installation issue, but realised I needed to add a line to change the working directory in order to use the relative paths. This should be fixed now, you'll just need to replace the old module files with the new ones.

Thanks for flagging this up!
