### ISSUE TITLE
Pandas error when no candidate peaks found

### ISSUE THREAD

**Issue by LHentges** [LHentges/LanceOtron#20]
LanceOtron should return an empty file (and possibly warn user) when no candidate peaks are found - currently error arises in this situation:

`ValueError: Length mismatch: Expected axis has 0 elements, new values have 19 elements`

**Comment by annajbott** [comment]
Hello, any update on this?

**Comment by annajbott** [comment]
@LHentges can you review my PR: https://github.com/LHentges/LanceOtron/pull/25

**Comment by LHentges** [comment]
Fixed with last PR
