### ISSUE TITLE
Version warnings

### ISSUE THREAD

**Issue by gitMakeCoffee** [LHentges/LanceOtron#23]
Ran LanceOtron successfully on some bigwigs.
However, got some warning messages at each iteration:
```
/home/username/.mamba/envs/lanceotron/lib/python3.10/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 0.23.1 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
```
Looks like there is a version issue.
LanceOtron was installed using Conda/Mamba.
What would be the ideal versions for its dependencies to avoid these messages?
Are the calls still reliable despite these warnings?
Thank you.

**Comment by francicco** [comment]
Same problem here.
Cheers
F
