### ISSUE TITLE
Calling peaks in single cell data

### ISSUE THREAD

**Issue by vravik** [LHentges/LanceOtron#5]
Hey guys,

I came to know about your tool while reading the PeakVI paper. I am interested in studying some single cell / single nucleus ATACseq data, and given your tool is significantly better than MACS, I was wondering if this could be used for calling peaks in this data as well? Are there any potential issues I must be aware of? Can I just feed the bigwig file from the single cell expt as input to call peaks?

**Comment by LHentges** [comment]
Hi @vravik,

The pattern of fragments seen with scATAC closely match ATAC, but generally with a much cleaner signal. We have seen LanceOtron perform just as well, if not better, on these tracks out of the box without any modification. This is assuming you're aggregating the cell samples into a single bam file, and making a bigwig file from that. 

My colleague is in the process of publishing a pipeline for improved scATAC resolution using LanceOtron, and I'm happy to keep you in the loop on that if you're interested (Lance.Hentges at imm.ox.ac.uk). If you have any other questions feel free to contact me either through GitHub or email! 

Best,

Lance
